name = "your-worker-name"
compatibility_date = "2025-05-04"

# Main entry point for the worker
main = "dist/index.html"  # This should be your generated HTML file after the build

# Configure assets directory to point to the build output
[assets]
directory = "./dist"  # Ensure this is the correct output directory for Vite

# Optionally specify the build command
[build]
command = "npm run build"  # Run Vite's build process
