name: Build and Deploy (React only, no dev index)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (safe)
        run: |
          npm config set legacy-peer-deps true
          npm ci || npm i

      - name: Build React app (Vite)
        env:
          CI: false
        run: npm run build

      - name: Prepare publish folder (use ONLY the build)
        shell: bash
        run: |
          rm -rf out
          mkdir -p out

          # ✅ Only use the built files from dist (never copy repo root index.html)
          cp -r dist/* out/

          # Optional static folders/files (safe to copy)
          for p in blog assets ar public images img css js robots.txt sitemap.xml CNAME MOJ.jpg; do
            [ -e "$p" ] && cp -r "$p" out/ || true
          done

          # SPA fallback so clean URLs work
          [ -f out/index.html ] && cp out/index.html out/404.html || true

          # Ensure Jekyll doesn't interfere
          echo > out/.nojekyll

          echo "---- OUT LISTING ----"
          ls -la out
          echo "---- JS BUNDLE ----"
          ls -la out/assets || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
