name: Build and Deploy (React + Blog + AR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (safe)
        run: |
          npm config set legacy-peer-deps true
          npm ci || npm i

      - name: Build React app
        env:
          CI: false
        run: |
          # Prefer your script; fall back to vite if script missing
          if npm run | grep -q "build"; then
            npm run build
          else
            npx vite build
          fi

      - name: Prepare publish folder
        shell: bash
        run: |
          mkdir -p out
          # Copy built React app
          if [ -d "dist" ]; then
            cp -r dist/* out/
          elif [ -d "build" ]; then
            cp -r build/* out/
          fi

          # Bring along static content if present
          for p in blog assets public ar blog.html robots.txt sitemap.xml CNAME MOJ.jpg; do
            [ -e "$p" ] && cp -r "$p" out/ || true
          done

          # SPA fallback so clean URLs work
          [ -f out/index.html ] && cp out/index.html out/404.html || true

          # ✅ FORCE CREATE .nojekyll (even if it isn't in your repo)
          echo > out/.nojekyll

          echo "Publish folder listing:"
          ls -la out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
