name: Build and Deploy (React + Static Blog)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Fixes your earlier peer-dependency error automatically
      - name: Install (safe)
        run: |
          npm config set legacy-peer-deps true
          npm ci || npm i

      - name: Build React app
        env:
          CI: false
        run: npm run build

      - name: Prepare publish folder (add static blog + SEO files)
        run: |
          mkdir -p out
          cp -r dist/* out/
          cp -r blog out/ || true
          cp -r assets out/ || true
          cp -r ar out/ || true
          cp blog.html out/ || true
          cp robots.txt out/ || true
          cp sitemap.xml out/ || true
          cp CNAME out/ || true
          cp MOJ.jpg out/ || true
          # Single-page-app fallback so clean URLs work
          cp out/index.html out/404.html || true
          echo "Publish folder contents:"; ls -la out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
