export const featuredBlogs = [
  {
    title: "Building Materials Supplier Saudi Arabia",
    href: "/blog/building-materials-supplier-saudi-arabia.html",
    category: "Building Materials",
    excerpt: "How MOJAF supports contractors with dependable finishing, fit-out and construction material supply across KSA.",
    image: "/about2.webp"
  },
  {
    title: "Construction Materials Supplier Riyadh",
    href: "/blog/construction-materials-riyadh.html",
    category: "Riyadh Supply",
    excerpt: "A practical guide for sourcing construction materials in Riyadh with faster lead times and better BOQ planning.",
    image: "/herobg.avif"
  },
  {
    title: "Fasteners Supplier Saudi Arabia",
    href: "/blog/fasteners-saudi-arabia.html",
    category: "Fasteners",
    excerpt: "Choose the right screws, anchors and fastening accessories for Saudi commercial, MEP and fit-out projects.",
    image: "/screwsth.png"
  },
  {
    title: "Wall Skirting Supplier Riyadh",
    href: "/blog/wall-skirting-supplier-riyadh.html",
    category: "Wall Skirting",
    excerpt: "Compare PS, PVC and MDF skirting profiles for clean handover finishes in Riyadh offices, villas and retail spaces.",
    image: "/psSkirting.png"
  },
  {
    title: "SPC Flooring Supplier Jeddah",
    href: "/blog/spc-flooring-supplier-jeddah.html",
    category: "SPC Flooring",
    excerpt: "What to check when selecting SPC flooring for Jeddah coastal projects, from wear layer to accessories.",
    image: "/pvcFlooring.png"
  },
  {
    title: "Portacabin Materials Supplier Saudi Arabia",
    href: "/blog/portacabin-materials-supplier-saudi-arabia.html",
    category: "Portacabin Materials",
    excerpt: "Core boards, insulation, doors, electrical and finishing materials for portacabin builders across Saudi Arabia.",
    image: "/doorth.png"
  }
];

export const additionalBlogLinks = [
  { title: "Adhesives & Trims that Match Your Skirting", href: "/blog/Adhesives-Trims-that-Match-Your-Skirting.html" },
  { title: "Aluminum Skirting Supplier Saudi Arabia", href: "/blog/aluminum-skirting-supplier-saudi-arabia.html" },
  { title: "Anchors & Fixings for Block and Concrete Walls", href: "/blog/Anchors-Fixings-for-Block-and-Concrete-Walls.html" },
  { title: "Building Material Distributors in KSA: What to Look For", href: "/blog/building-material-distributors-ksa.html" },
  { title: "Building Materials Supplier Dammam", href: "/blog/building-materials-supplier-dammam.html" },
  { title: "Building Materials Supplier Jeddah", href: "/blog/building-materials-supplier-jeddah.html" },
  { title: "Building Materials Supplier Riyadh", href: "/blog/building-materials-supplier-riyadh.html" },
  { title: "Cement Board Supplier in KSA", href: "/blog/cement-board-supplier-ksa.html" },
  { title: "How to Choose a Reliable Building Materials Supplier in KSA", href: "/blog/choose-building-materials-supplier-ksa.html" },
  { title: "Common Installation Mistakes and How to Avoid Them", href: "/blog/Common-Installation-Mistakes-and-How-to-Avoid-Them.html" },
  { title: "Construction Fasteners Dammam", href: "/blog/construction-fasteners-dammam.html" },
  { title: "Construction Materials Dammam", href: "/blog/construction-materials-dammam.html" },
  { title: "Construction Materials Jeddah", href: "/blog/construction-materials-jeddah.html" },
  { title: "Construction Materials in Riyadh: Top 5 Trends in 2025", href: "/blog/construction-materials-riyadh-trends-2025.html" },
  { title: "Gypsum Board Supplier in Dammam — Types & Use Cases", href: "/blog/dammam-gypsum-board-supplier.html" },
  { title: "Portacabin Materials Supplier in Dammam — Boards, Electrical & Insulation", href: "/blog/dammam-portacabin-materials-supplier.html" },
  { title: "Screws & Fasteners Supplier in Dammam — MEP & Fit-Out", href: "/blog/dammam-screws-fasteners-supplier.html" },
  { title: "SPC Flooring Supplier in Dammam/Khobar — Industrial & Retail", href: "/blog/dammam-spc-flooring-supplier.html" },
  { title: "Wall Skirting Supplier in Dammam/Khobar — MDF & PS", href: "/blog/dammam-wall-skirting-supplier.html" },
  { title: "Decorative Skirting Boards in KSA: MDF, PS, Modern Designs", href: "/blog/decorative-skirting-boards-ksa.html" },
  { title: "FAQ: MOJAF Building Materials — Ordering & Delivery", href: "/blog/FAQ-MOJAF-Building-Materials-Ordering-Delivery.html" },
  { title: "Fasteners Buyer’s Guide for Contractors in Saudi Arabia", href: "/blog/Fasteners-Buyers-Guide-for-Contractors-in-Saudi-Arabia.html" },
  { title: "Fasteners Dammam", href: "/blog/fasteners-dammam.html" },
  { title: "Fasteners in Dammam: Industrial vs. Residential Needs", href: "/blog/Fasteners-in-Dammam-Industrial-vs-Residential-Needs.html" },
  { title: "Fasteners in Jeddah: Typical Stock & Lead Times", href: "/blog/Fasteners-in-Jeddah-Typical-Stock-Lead-Times.html" },
  { title: "Fasteners in Riyadh: BOQ Tips & Compliance", href: "/blog/Fasteners-in-Riyadh-BOQ-Tips-Compliance.html" },
  { title: "Fasteners Jeddah", href: "/blog/fasteners-jeddah.html" },
  { title: "Fasteners Riyadh", href: "/blog/fasteners-riyadh.html" },
  { title: "Fasteners Supplier in Dammam: Grades & Coastal Durability", href: "/blog/fasteners-supplier-dammam.html" },
  { title: "Fasteners Supplier in Jeddah", href: "/blog/fasteners-supplier-jeddah.html" },
  { title: "Floor Skirting Dealer in Riyadh: Practical Buyer’s Guide", href: "/blog/floor-skirting-dealer-riyadh.html" },
  { title: "Gypsum Board Supplier in Dammam", href: "/blog/gypsum-board-supplier-dammam.html" },
  { title: "Gypsum & Cement Boards — Selection for Partitions & Ceilings", href: "/blog/Gypsum-Cement-Boards-Selection-for-Partitions-Ceilings.html" },
  { title: "Hex Bolts Supplier KSA", href: "/blog/hex-bolts-supplier-ksa.html" },
  { title: "Hex Bolts vs. Self-Drilling Screws — When to Use Each", href: "/blog/Hex-Bolts-vs-Self-Drilling-Screws-When-to-Use-Each.html" },
  { title: "How to Estimate Wastage for Flooring & Skirting", href: "/blog/How-to-Estimate-Wastage-for-Flooring-Skirting.html" },
  { title: "How to Request a Quote (What to Share)", href: "/blog/How-to-Request-a-Quote-What-to-Share.html" },
  { title: "Industrial Screws KSA", href: "/blog/industrial-screws-ksa.html" },
  { title: "Interior Finishing Materials in Saudi Arabia: Skirting, Flooring, Profiles", href: "/blog/interior-finishing-materials-ksa.html" },
  { title: "Screws & Fasteners Supplier in Jeddah — Coastal Protection", href: "/blog/jeddah-screws-fasteners-supplier.html" },
  { title: "SPC Flooring Supplier in Jeddah — Coastal Projects Ready", href: "/blog/jeddah-spc-flooring-supplier.html" },
  { title: "Wall Skirting Supplier in Jeddah — MDF & PS", href: "/blog/jeddah-wall-skirting-supplier.html" },
  { title: "Rock Wool Insulation Supplier in KSA — Slabs & Blankets", href: "/blog/ksa-rock-wool-insulation-supplier.html" },
  { title: "LVT Flooring Supplier in Jeddah", href: "/blog/lvt-flooring-supplier-jeddah.html" },
  { title: "LVT Flooring Supplier in Madinah — Quiet, Durable Floors", href: "/blog/madinah-lvt-flooring-supplier.html" },
  { title: "LVT Flooring Supplier in Makkah — Hospitality & Residential", href: "/blog/makkah-lvt-flooring-supplier.html" },
  { title: "MDF Skirting Boards in Saudi Arabia", href: "/blog/mdf-skirting-boards-saudi-arabia.html" },
  { title: "MDF Skirting Supplier KSA", href: "/blog/mdf-skirting-supplier-ksa.html" },
  { title: "Why Portacabin Materials Are Surging in Jeddah and Dammam", href: "/blog/portacabin-materials-demand.html" },
  { title: "Portacabin Materials in Khobar: Checklist for Procurement", href: "/blog/portacabin-materials-khobar.html" },
  { title: "PS Skirting Supplier in KSA", href: "/blog/ps-skirting-supplier-ksa.html" },
  { title: "PVC Flooring Project Guide KSA", href: "/blog/pvc-flooring-project-guide-ksa.html" },
  { title: "PVC Skirting Boards KSA", href: "/blog/pvc-skirting-boards-ksa.html" },
  { title: "Quality Fasteners in Saudi Construction: What Really Matters", href: "/blog/quality-fasteners-saudi-arabia.html" },
  { title: "Cement Board Supplier in Riyadh — Wet Areas & Facades", href: "/blog/riyadh-cement-board-supplier.html" },
  { title: "Screws & Fasteners Supplier in Riyadh — Specs that Last", href: "/blog/riyadh-screws-fasteners-supplier.html" },
  { title: "SPC Flooring Supplier in Riyadh — Stock, Specs & Delivery", href: "/blog/riyadh-spc-flooring-supplier.html" },
  { title: "Wall Skirting Supplier in Riyadh — MDF & PS Profiles", href: "/blog/riyadh-wall-skirting-supplier.html" },
  { title: "Rock Wool Insulation Supplier in KSA", href: "/blog/rock-wool-insulation-supplier-ksa.html" },
  { title: "Screw Types Every Riyadh Contractor Should Know", href: "/blog/screw-types-riyadh.html" },
  { title: "Screws Selection Guide KSA", href: "/blog/screws-selection-guide-ksa.html" },
  { title: "Screws Supplier in Riyadh", href: "/blog/screws-supplier-riyadh.html" },
  { title: "Screws, Washers, Nuts: Getting Grade & Finish Right", href: "/blog/Screws-Washers-Nuts-Getting-Grade-Finish-Right.html" },
  { title: "Site Delivery Planning — Phased Drops for Large Jobs", href: "/blog/Site-Delivery-Planning-Phased-Drops-for-Large-Jobs.html" },
  { title: "SPC Flooring Dammam", href: "/blog/spc-flooring-dammam.html" },
  { title: "SPC Flooring for Retail & Offices — Specification Checklist", href: "/blog/SPC-Flooring-for-Retail-Offices-Specification-Checklist.html" },
  { title: "SPC Flooring Jeddah", href: "/blog/spc-flooring-jeddah.html" },
  { title: "SPC Flooring Riyadh", href: "/blog/spc-flooring-riyadh.html" },
  { title: "SPC Flooring Supplier in Riyadh", href: "/blog/spc-flooring-supplier-riyadh.html" },
  { title: "SPC & Vinyl Flooring Supplier Saudi Arabia", href: "/blog/spc-vinyl-flooring-supplier-saudi-arabia.html" },
  { title: "Stainless vs. Galvanized Fasteners in Coastal Cities", href: "/blog/Stainless-vs-Galvanized-Fasteners-in-Coastal-Cities.html" },
  { title: "Construction Supply Chains in KSA: Risks and Workarounds", href: "/blog/supply-chain-challenges-ksa.html" },
  { title: "Sustainable Construction Materials in Saudi Arabia", href: "/blog/sustainable-materials-ksa.html" },
  { title: "Sustainable Skirting & Flooring Options in Saudi Construction", href: "/blog/sustainable-skirting-flooring-ksa.html" },
  { title: "Top 10 Fast-Moving SKUs for Fit-Out Projects", href: "/blog/Top-10-Fast-Moving-SKUs-for-Fit-Out-Projects.html" },
  { title: "Top Fasteners, Nuts & Bolts Suppliers in Saudi Arabia (2025): Why MOJAF Ranks #1", href: "/blog/top-fasteners-suppliers-saudi-arabia-2025.html" },
  { title: "Underlay & Acoustic Considerations for SPC", href: "/blog/Underlay-Acoustic-Considerations-for-SPC.html" },
  { title: "Vinyl Flooring Buyer’s Guide KSA", href: "/blog/vinyl-flooring-buyers-guide-ksa.html" },
  { title: "Vinyl & LVT Flooring Distributor in KSA", href: "/blog/vinyl-flooring-distributor-ksa.html" },
  { title: "Wall Skirting Dammam", href: "/blog/wall-skirting-dammam.html" },
  { title: "Wall Skirting Installation Guide KSA", href: "/blog/wall-skirting-installation-guide-ksa.html" },
  { title: "Wall Skirting Jeddah", href: "/blog/wall-skirting-jeddah.html" },
  { title: "Wall Skirting Materials (PVC, MDF, Aluminum) — Pros & Cons", href: "/blog/Wall-Skirting-Materials-PVC-MDF-Aluminum-Pros-Cons.html" },
  { title: "Wall Skirting Riyadh", href: "/blog/wall-skirting-riyadh.html" },
  { title: "Wall Skirting Supplier in Jeddah: PVC vs MDF vs Aluminum", href: "/blog/wall-skirting-supplier-jeddah.html" },
  { title: "Wall Skirting in KSA: Types, Trends and Practical Specs", href: "/blog/wall-skirting-trends-ksa.html" },
  { title: "Warehouse Stock Checks: What Affects Pricing", href: "/blog/Warehouse-Stock-Checks-What-Affects-Pricing.html" },
  { title: "Washers & Nuts Supplier KSA", href: "/blog/washers-nuts-supplier-ksa.html" },
  { title: "Wholesale Building Materials in Jubail: Where Contractors Buy", href: "/blog/wholesale-building-materials-jubail.html" }
];
