name: build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect Node project
        id: detect
        shell: bash
        run: |
          if [ -f package.json ]; then
            echo "has_pkg=true" >> $GITHUB_OUTPUT
            if node -e "try{const p=require('./package.json');process.stdout.write(p.scripts&&p.scripts.build?'yes':'no')}catch(e){process.stdout.write('no')}" | grep -q yes; then
              echo "has_build=true" >> $GITHUB_OUTPUT
            else
              echo "has_build=false" >> $GITHUB_OUTPUT
            fi
            if [ -f package-lock.json ]; then echo "has_lock=true" >> $GITHUB_OUTPUT; else echo "has_lock=false" >> $GITHUB_OUTPUT; fi
          else
            echo "has_pkg=false" >> $GITHUB_OUTPUT
            echo "has_build=false" >> $GITHUB_OUTPUT
            echo "has_lock=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: ${{ steps.detect.outputs.has_pkg == 'true' && steps.detect.outputs.has_build == 'true' }}
        with:
          node-version: 18
          cache: npm

      - name: Install deps with safe fallback
        if: ${{ steps.detect.outputs.has_pkg == 'true' && steps.detect.outputs.has_build == 'true' }}
        shell: bash
        run: |
          set +e
          if [ "${{ steps.detect.outputs.has_lock }}" = "true" ]; then
            echo "Trying npm ci (lockfile present)..."
            npm ci
            CI_STATUS=$?
            if [ "$CI_STATUS" -ne 0 ]; then
              echo "npm ci failed (lockfile mismatch). Falling back to npm install..."
              npm install --no-audit --no-fund
            fi
          else
            echo "No lockfile found. Running npm install..."
            npm install --no-audit --no-fund
          fi
          set -e

      - name: Build
        if: ${{ steps.detect.outputs.has_pkg == 'true' && steps.detect.outputs.has_build == 'true' }}
        run: npm run build

      - name: Skip (no Node build here)
        if: ${{ steps.detect.outputs.has_pkg != 'true' || steps.detect.outputs.has_build != 'true' }}
        run: echo "No package.json with build script; skipping build."
