name: Build and Deploy (Vite + Static)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build (handles peer-deps safely)
        run: |
          if [ -f package.json ]; then
            npm ci --legacy-peer-deps || npm i --legacy-peer-deps
            npm run build
          else
            echo "No package.json found — skipping Vite build"
          fi

      - name: Prepare publish folder
        run: |
          mkdir -p out
          # If Vite produced /dist, use it
          if [ -d dist ]; then
            cp -r dist/* out/
          fi
          # Always include static content
          cp -r blog out/ || true
          cp -r assets out/ || true
          cp -r ar out/ || true
          cp blog.html out/ || true
          cp 404.html out/ || true
          cp sitemap.xml out/ || true
          cp robots.txt out/ || true
          cp CNAME out/ || true
          cp MOJ.jpg out/ || true
          # Fallback: ensure index.html exists
          if [ ! -f out/index.html ] && [ -f index.html ]; then
            cp index.html out/
          fi
          echo "Publish folder contents:"
          ls -la out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
