name: Repair Site Paths, Cleanup & Rebuild
on:
  workflow_dispatch:

jobs:
  repair:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Ensure a real homepage at repo root
      - name: Ensure root index.html matches site homepage
        shell: bash
        run: |
          set -euo pipefail
          if [ -f public/index.html ]; then
            cp public/index.html index.html
          fi

      # 2) Fix paths using Python (no shell quoting issues)
      - name: Rewrite HTML paths (Python)
        run: |
          python3 - <<'PY'
          import os, re
          SKIP_PREFIXES = ('./.git','./.github','./node_modules','./public','./meta-tags','./_turbo_en','./blogs')
          def should_skip(root):
              rp = './' + os.path.relpath(root, '.').replace('\\','/')
              return any(rp.startswith(p) for p in SKIP_PREFIXES)
          for root, _, files in os.walk('.'):
              if should_skip(root): 
                  continue
              for fn in files:
                  if not fn.endswith('.html'): 
                      continue
                  p = os.path.join(root, fn)
                  try:
                      s = open(p,'r',encoding='utf-8',errors='ignore').read()
                  except Exception:
                      continue
                  # remove <base href="/public/">
                  s = re.sub(r'<base[^>]*href=["\']/?public/?["\'][^>]*>\s*','',s, flags=re.I)
                  # /public/... -> /...
                  s = re.sub(r'(href|src)=["\']/?public/([^"\']*)', r'\1="/\2', s, flags=re.I)
                  # assets|css|js|images|img -> absolute
                  s = re.sub(r'(href|src)=["\'](assets|css|js|images|img)/([^"\']*)', r'\1="/\2/\3', s, flags=re.I)
                  # blog & blog.html -> /blog/
                  s = re.sub(r'href=["\']/?blog(?:\.html)?["\']', 'href="/blog/"', s, flags=re.I)
                  open(p,'w',encoding='utf-8').write(s)
          print("Rewrites done.")
          PY

      # 3) Remove duplicate sources that confuse the site
      - name: Remove duplicate folders
        shell: bash
        run: |
          set -euo pipefail
          rm -rf public meta-tags _turbo_en blogs || true

      # 4) Rebuild sitemap.xml & robots.txt
      - name: Generate sitemap & robots
        shell: bash
        run: |
          set -euo pipefail
          BASE="https://mojaf-sa.com"
          TODAY="$(date +%F)"
          TMP="$(mktemp)"

          find . \
            -type d \( -path './.git' -o -path './.github' -o -path './node_modules' -o -path './public' -o -path './meta-tags' -o -path './_turbo_en' -o -path './blogs' \) -prune -false -o \
            -type f -name '*.html' \
          | while read -r f; do
              f="${f#./}"; bn="$(basename "$f")"
              case "$f" in 404.html|header-footer-snippet.html|blog.html) continue;; esac
              if [ "$bn" = "index.html" ]; then
                d="$(dirname "$f")"; [ "$d" = "." ] && url="$BASE/" || url="$BASE/$d/"
              else
                url="$BASE/$f"
              fi
              [ "$url" = "$BASE/blog" ] || [ "$url" = "$BASE/blog.html" ] && url="$BASE/blog/"
              url="${url//\/\//\/}"; url="${url/:\//:\/\/}"
              echo "$url" >> "$TMP"
            done

          sort -u "$TMP" > "$TMP.sorted"
          {
            echo '<?xml version="1.0" encoding="UTF-8"?>'
            echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            while read -r u; do
              printf '  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n  </url>\n' "$u" "$TODAY"
            done < "$TMP.sorted"
            echo '</urlset>'
          } > sitemap.xml

          {
            echo 'User-agent: *'
            echo 'Allow: /'
            echo
            echo "Sitemap: ${BASE}/sitemap.xml"
          } > robots.txt

      - name: Commit & push
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "fix: homepage, path rewrites (python), remove duplicates, rebuild sitemap/robots"
            git push
          else
            echo "No changes to commit"
          fi
