name: Repair Site Paths, Cleanup & Rebuild
on:
  workflow_dispatch:

jobs:
  repair:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Make the homepage the real one (copy from public/index.html if needed)
      - name: Ensure root index.html matches site homepage
        shell: bash
        run: |
          set -euo pipefail
          if [ -f public/index.html ]; then
            cp public/index.html index.html
          fi

      # 2) Fix blank-page causes (Perl-only, no sed)
      - name: Rewrite HTML paths (Perl only)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          for f in **/*.html; do
            perl -0777 -i -pe '
              s/<base[^>]*href=["\']\/?public\/?["\'][^>]*>\s*//ig;                             # remove <base href="/public/">
              s/(href|src)=["\']\/?public\/([^"\']*)/$1="\/$2/ig;                               # /public/... -> /...
              s/(href|src)=["\'](assets|css|js|images|img)\/([^"\']*)/$1="\/$2\/$3/ig;          # assets -> /assets
              s/href=["\']\/?blog(?:\.html)?["\']/href="\/blog\/"/ig;                           # blog(.html) -> /blog/
            ' "$f"
          done
          echo "Rewrites done."

      # 3) Remove duplicate sources that confuse the site
      - name: Remove duplicate folders
        shell: bash
        run: |
          set -euo pipefail
          rm -rf public meta-tags _turbo_en blogs || true

      # 4) Rebuild sitemap.xml & robots.txt (clean)
      - name: Generate sitemap & robots
        shell: bash
        run: |
          set -euo pipefail
          BASE="https://mojaf-sa.com"
          TODAY="$(date +%F)"
          TMP="$(mktemp)"

          find . \
            -type d \( -path './.git' -o -path './.github' -o -path './node_modules' -o -path './public' -o -path './meta-tags' -o -path './_turbo_en' -o -path './blogs' \) -prune -false -o \
            -type f -name '*.html' \
          | while read -r f; do
              f="${f#./}"; bn="$(basename "$f")"
              case "$f" in 404.html|header-footer-snippet.html|blog.html) continue;; esac
              if [ "$bn" = "index.html" ]; then
                d="$(dirname "$f")"; [ "$d" = "." ] && url="$BASE/" || url="$BASE/$d/"
              else
                url="$BASE/$f"
              fi
              [ "$url" = "$BASE/blog" ] || [ "$url" = "$BASE/blog.html" ] && url="$BASE/blog/"
              url="${url//\/\//\/}"; url="${url/:\//:\/\/}"
              echo "$url" >> "$TMP"
            done

          sort -u "$TMP" > "$TMP.sorted"
          {
            echo '<?xml version="1.0" encoding="UTF-8"?>'
            echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
            while read -r u; do
              printf '  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n  </url>\n' "$u" "$TODAY"
            done < "$TMP.sorted"
            echo '</urlset>'
          } > sitemap.xml

          {
            echo 'User-agent: *'
            echo 'Allow: /'
            echo
            echo "Sitemap: ${BASE}/sitemap.xml"
          } > robots.txt

      - name: Commit & push
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "fix: homepage, asset paths, remove duplicates, rebuild sitemap/robots (perl-only)"
            git push
          else
            echo "No changes to commit"
          fi
