name: Repo Health (SEO & HTML)

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'Canonical base URL (e.g., https://example.com)'
        required: false
        default: 'https://mojaf-sa.com'
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      SITE_URL: ${{ inputs.site_url || 'https://mojaf-sa.com' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (robust)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm i
          else
            npm init -y >/dev/null 2>&1
            npm i jsdom@^24 --no-audit --no-fund
          fi

      - name: Run audit (report only)
        run: npm run audit:seo || node scripts/audit-and-fix.mjs || true

      - name: Apply fixes
        run: |
          npm run fix:seo || node scripts/audit-and-fix.mjs --fix || true
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b repo-health/fixes
            git add -A
            git commit -m "chore(repo-health): canonical normalization & dup-page report"
            git push --force --set-upstream origin repo-health/fixes
          fi

      - name: Open PR if branch exists
        if: always()
        run: |
          if git ls-remote --exit-code --heads origin repo-health/fixes; then
            gh pr create --title "Repo Health: canonical fixes & duplicate-page report" \
              --body "Automated canonical tag normalization and duplicate-page report." \
              --base main --head repo-health/fixes || true
          fi
